### ISSUE TITLE
About the trained model

### ISSUE THREAD

**Issue by GilgameshD** [vincekurtz/CollisionAvoidance#2]
Hi, thanks for your wonderful work!

When I run your code, I notice that the pre-trained model is missing. Could you please provide a pre-trained model?

**Comment by vincekurtz** [comment]
Hi @GilgameshD, thanks for your interest! 

I initially didn't provide a pre-trained model since I was mainly interested in the training process. I've updated the repo with a sample model now. It's based on only a few minutes of training on my laptop, so not the best policy but it's a starting point. I would recommend training your own model, which can be done with `roslaunch collision_avoidance rl_controller.launch`. Then you can use `test_trained_model.launch` to evaluate that (new) model.

**Comment by GilgameshD** [comment]
Thanks a lot !
